default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: aces_development
test:
  <<: *default
  database: aces_test
production:
  <<: *default
  database: aces_production
  username: aces
  password: <%= ENV['ACES_DATABASE_PASSWORD'] %>
